### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by Poffen** [runcmf/runbb#1]
Hi,
I've tried to install the current dev version of runbb according to your description (with slim skeleton), but I get a fatal error when I navigate to index.php: `Fatal error: Uncaught InvalidArgumentException: Identifier "log" is not defined.`

**Comment by 1f7** [comment]
Hi @Poffen,
For answer I need simulate this error.
Possible this error with logger, but need more info.
Can you show more error lines?
In which step this error, when install or after?
If forum not configured core must redirect you to install, not index.php
Try delete `index.php` from URL

**Comment by Poffen** [comment]
Here is the the complete error output: `
Fatal error: Uncaught InvalidArgumentException: Identifier "log" is not defined. in /var/www/html/runbb/vendor/pimple/pimple/src/Pimple/Container.php:96 Stack trace: #0 [internal function]: Pimple\Container->offsetGet('log') #1 /var/www/html/runbb/vendor/runcmf/runbb/src/RunBB/Core/Statical/Manager.php(244): call_user_func_array(Array, Array) #2 /var/www/html/runbb/vendor/runcmf/runbb/src/RunBB/Core/Statical/BaseProxy.php(48): RunBB\Core\Statical\Manager->getProxyTarget('RunBB\\Core\\Inte...') #3 /var/www/html/runbb/vendor/runcmf/runbb/src/RunBB/Core/Statical/BaseProxy.php(60): RunBB\Core\Statical\BaseProxy::getInstance() #4 /var/www/html/runbb/vendor/runcmf/runbb/src/RunBB/Init.php(217): RunBB\Core\Statical\BaseProxy::__callStatic('error', Array) #5 [internal function]: RunBB\Init->RunBB\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(TypeError)) #6 /var/www/html/runbb/vendor/slim/slim/Slim/App.php(671): call_user_func_array(Object(Closure), Array) #7 /var/www/html/runbb/vendor/slim/slim/Slim/App. in /var/www/html/runbb/vendor/pimple/pimple/src/Pimple/Container.php on line 96
`
This occurs when I hit public/index.php for the first time to perform installation, and I never get beyond this stage.

**Comment by 1f7** [comment]
Hi @Poffen,
I commit small fix for renderer and runbb, please `composer update`
Thank you.

**Comment by Poffen** [comment]
Hi again,

Almost there ... I applied the fix, but I first got a new error related to creation of the database. I looked into phpmyadmin og found that the 'logs' and the 'users' tables were missing. The error I got was related to the 'logs' table:

`#1101 - BLOB, TEXT, GEOMETRY or JSON column 'message' can't have a default value`

And this was the case also for the 'context' and 'extra' columns. 

So I then manually deleted the setting ` DEFAULT ''` for both the 'message', 'context' and 'extra' columns in the install.php file and tried reinstalling the script. I was now able to install all tables, but I had some other issues which I couldn't solve. So I made a completely new install of the slim-skeleton as well as the updated version of runbb and changed the column settings manually (as indicated above) before installing the script. All tables now seemed to be installed correctly, but I got a blank index page (../public/forum) again. So I turned error reporting on and got this error message:

`Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #9 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'runbb.ltwith.msgstr' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by in /var/www/html/runbb/vendor/j4mie/idiorm/idiorm.php:503 Stack trace: #0 /var/www/html/runbb/vendor/j4mie/idiorm/idiorm.php(503): PDOStatement->execute() #1 /var/www/html/runbb/vendor/j4mie/idiorm/idiorm.php(1906): ORM::_execute('SELECT `lt`.*, ...', Array, 'default') #2 /var/www/html/runbb/vendor/j4mie/idiorm/idiorm.php(737): ORM->_run() #3 /var/www/html/runbb/vendor/j4mie/idiorm/idiorm.php(2261): ORM->find_array() #4 /var/www/html/runbb/vendor/runcmf/runbb/src/RunBB/Model/Admin/Languages.php(127): ORM->__call('findArray', Array) #5 /var/www/html/runbb/vendor/runcmf/runbb/src/RunBB/Model/Admin/Languages.php(209): RunBB\Model\Admin\Languages->getTranslationsByDomain('1', 'login') #6 /var/www/html/runbb/ in /var/www/html/runbb/vendor/j4mie/idiorm/idiorm.php on line 503`

Hope this helps :)
Poffen

**Comment by Poffen** [comment]
Update on the last error message:

Just to let you know... The fatal error was caused by the setting 'only_full_group_by' in my mysql config file (I'm using version 5.7.17). I removed this setting in the config file and the problem was solved at my end. It may still though be something to look into, as this may likely cause problems for others. 

In any case, I'm up and running after the small changes I made to the install file. :)

Poffen

**Comment by 1f7** [comment]
Today reinstall all my dev scripts and not found errors You write.

local db:
```sh
[12:28 ]-[vagrant@run1]-[~] 
$ mysql -V
mysql  Ver 15.1 Distrib 10.2.5-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```
hosting db, also no problem:
```sh
mysql  Ver 14.14 Distrib 5.1.73, for portbld-freebsd8.4 (i386) using  5.2
```
but I fix in queries some `group_by`

thanks for the info.
